### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by Atul-Kumar-Jena** [1itromio/cowin-vaccine-booking#2]
Error: No beneficiary found for provided beneficiary mobile number <my number here>.

got this pop-up several times after requesting for otp.. After that it didn't appear..

**Comment by 1itromio** [comment]
This is  not a bug. No beneficiary means you have not added the beneficiaries. First add the beneficiaries from cowin [here](https://www.cowin.gov.in/). Read the README.md first.
